assembly_info:
  patch: false

install:
  - choco install gitversion.portable -pre -y

before_build:
- nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
- ps: Update-AppveyorBuild -Version $env:GitVersion_NuGetVersion

build:
  publish_nuget: true
  verbosity: minimal