assembly_info:
  patch: false

install:
  - choco install gitversion.portable -pre -y

before_build:
- nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  publish_nuget: true
  verbosity: minimal