assembly_info:
  patch: false

install:
  - choco install gitversion.portable -pre -y

before_build:
- nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
- ps: Update-AppveyorBuild -Version $env:GitVersion_NuGetVersion

build:
  publish_nuget: false
  verbosity: minimal

on_success:
  - cmd: nuget pack src\Toggled\Toggled.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Toggled.%GitVersion_NuGetVersion%.nupkg"